FROM kazik.aws.tshdev.io/tsh/docker/php:7.4.2-latest as php

RUN php-install {{ phpExtensions|join(" ") }}; \
    set -eux; \
    addgroup -g 82 -S www-data; \
    adduser -u 82 -D -S -G www-data www-data; \
    mkdir /opt/app/;

WORKDIR /opt/app/
USER www-data

FROM php as php_builder

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# install Symfony Flex globally to speed up download of Composer packages (parallelized prefetching)
RUN set -eux; \
    composer global require "symfony/flex" --prefer-dist --no-progress --no-suggest --classmap-authoritative; \
    composer clear-cache
ENV PATH="${PATH}:/www-data/.composer/vendor/bin"

ARG APP_ENV=prod

COPY ./ ./build
USER root
RUN  chown -R www-data:www-data /opt/app/
USER www-data

RUN set -eux; \
    cd build; \
    rm -f -R var/cache var/log; \
    mkdir -p var/cache var/log; \
    chmod -f +x bin/console || true; \
    composer run-script --no-dev post-install-cmd; \
    composer install --prefer-dist --no-dev --no-scripts --no-progress --no-suggest; \
    composer dump-autoload --classmap-authoritative --no-dev; \
    composer clear-cache; \
    composer dump-env prod; \
    mkdir -p prod; \
    cp /opt/app/build/bin /opt/app/prod/bin; \
    cp /opt/app/build/config /opt/app/prod/config; \
    cp /opt/app/build/public /opt/app/prod/public; \
    cp /opt/app/build/src /opt/app/prod/src; \
    cp /opt/app/build/var /opt/app/prod/var; \
    cp /opt/app/build/vendor /opt/app/prod/vendor; \
    cp /opt/app/build/.env.local.php /opt/app/prod/.env.local.php;

FROM php as app_prod

COPY --from=php_builder /opt/app/prod /

USER root
HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD ["docker-healthcheck"]
EXPOSE 9000
CMD ["php-fpm"]


FROM nginx:1.17-alpine AS nginx

COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /opt/app

COPY --from=app_prod /opt/app/public ./public

FROM app_prod as app_dev_test