
bash:
	docker-compose up -d php
	docker-compose exec php sh

docker-build-image:
	docker build --no-cache --target php_app --file ./docker/Dockerfile --tag kazik.aws.tshdev.io/{{ clientName|lower }}/{{ projectName|lower }}/php_app:latest .
	docker build --target nginx_app --file ./docker/Dockerfile --tag kazik.aws.tshdev.io/{{ clientName|lower }}/{{ projectName|lower }}/nginx_app:latest .

docker-push-image:
	docker tag kazik.aws.tshdev.io/{{ clientName|lower }}/{{ projectName|lower }}/php_app:latest kazik.aws.tshdev.io/{{ clientName|lower }}/{{ projectName|lower }}/php_app:${DOCKER-IMAGE-VERSION}
	docker tag kazik.aws.tshdev.io/{{ clientName|lower }}/{{ projectName|lower }}/nginx_app:latest kazik.aws.tshdev.io/{{ clientName|lower }}/{{ projectName|lower }}/nginx_app:${DOCKER-IMAGE-VERSION}
	docker push kazik.aws.tshdev.io/{{ clientName|lower }}/{{ projectName|lower }}/php_app:${DOCKER-IMAGE-VERSION}
	docker push kazik.aws.tshdev.io/{{ clientName|lower }}/{{ projectName|lower }}/nginx_app:${DOCKER-IMAGE-VERSION}