version: "3.1"
services:
  app:

    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command:  sh -c " lsof +D ./project; rm -Rf ./project ; ./bin/console project:generate"
    #      command: ./bin/console project:generate -vvv
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
      - ./project:/opt/app/project

  phpqa:
    image: jakzal/phpqa:1.29.0-php7.4
    restart: "no"
    volumes:
      - ./:/project
      - ./var/tmp-phpqa:/tmp
    working_dir: /project