version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: app
    command:  sh -c " lsof +D ./project; rm -Rf ./project ; ./bin/console project:generate -vvv"
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
      - ./project:/opt/app/project

  phpqa:
    image: szula.aws.tshdev.io/jakzal/phpqa:1.29.0-php7.4
    restart: "no"
    volumes:
      - ./:/project
      - ./var/tmp-phpqa:/tmp
    working_dir: /project