FROM nginx:1.17-alpine AS nginx
COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /opt/app


FROM piotrbrzezina/php-binary:7.4.1-fpm as php

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD ["docker-healthcheck"]
EXPOSE 9000
CMD ["php-fpm"]

RUN php-install {{ phpExtensions|join(" ") }}; \
set -eux; \
addgroup -g 82 -S www-data; \
adduser -u 82 -D -S -G www-data www-data; \
mkdir /opt/app/;

WORKDIR /opt/app/

FROM php as builder
ENV COMPOSER_ALLOW_SUPERUSER=1
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN set -eux; \
composer global require "symfony/flex" --prefer-dist --no-progress --no-suggest --classmap-authoritative; \
composer clear-cache
ENV PATH="${PATH}:/root/.composer/vendor/bin"


FROM builder as build
ARG APP_ENV=prod
ENV APP_ENV=$APP_ENV
COPY ./ ./
RUN set -eux; \
composer install --no-dev  --prefer-dist --no-scripts --no-progress --no-suggest; \
rm -f -R var/cache var/log; \
mkdir -p var/cache var/log; \
chmod -f +x bin/console || true; \
composer dump-autoload --classmap-authoritative --no-dev; \
composer run-script --no-dev post-install-cmd; \
composer clear-cache; \
composer dump-env prod; \
mkdir -p /opt/app/prod; \
cp -r /opt/app/bin /opt/app/prod; \
cp -r /opt/app/config /opt/app/prod; \
cp -r /opt/app/src /opt/app/prod; \
cp -r /opt/app/var /opt/app/prod; \
cp -r /opt/app/vendor /opt/app/prod; \
cp -r /opt/app/public /opt/app/prod; \
cp /opt/app/.env.local.php /opt/app/prod/.env.local.php;


FROM php as app
COPY --from=build /opt/app/prod /opt/app/
RUN chown -R www-data:www-data /opt/app/

FROM nginx AS nginx_app
COPY --from=app /opt/app/public ./public