FROM piotrbrzezina/php-binary:7.4.1-fpm as php

RUN php-install {{ phpExtensions|join(" ") }}; \

set -eux; \
addgroup -g 82 -S www-data; \
adduser -u 82 -D -S -G www-data www-data; \
mkdir /opt/app/;

WORKDIR /opt/app/
USER www-data

FROM php as php_builder

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# install Symfony Flex globally to speed up download of Composer packages (parallelized prefetching)
RUN set -eux; \
composer global require "symfony/flex" --prefer-dist --no-progress --no-suggest --classmap-authoritative; \
composer clear-cache
ENV PATH="${PATH}:/www-data/.composer/vendor/bin"
ARG APP_ENV=prod
COPY composer.json comspoer.lock symfony.lock ./
RUN set -eux;\
cd build; \
[ "$APP_ENV" = prod ] && COMPOSER_NO_DEV_PARAM='--no-dev '  || COMPOSER_NO_DEV_PARAM='' ; \
composer install "$COMPOSER_NO_DEV_PARAM"--prefer-dist --no-scripts --no-progress --no-suggest;

COPY ./ ./
RUN set -eux; \
rm -f -R var/cache var/log; \
mkdir -p var/cache var/log; \
chmod -f +x bin/console || true; \
composer dump-autoload "$COMPOSER_NO_DEV_PARAM"--classmap-authoritative ; \
composer run-script "$COMPOSER_NO_DEV_PARAM"post-install-cmd; \
composer clear-cache; \
composer dump-env "$APP_ENV"; \

FROM php as app

COPY --from=php_builder /opt/app/ ./build
RUN set -eux; \
cp -r /opt/app/build/bin /opt/app/bin; \
cp -r /opt/app/build/config /opt/app/config; \
cp -r /opt/app/build/public /opt/app/public; \
cp -r /opt/app/build/src /opt/app/src; \
cp -r /opt/app/build/var /opt/app/var; \
cp -r /opt/app/build/vendor /opt/app/vendor; \
cp -r /opt/app/build/templates /opt/app/templates; \
cp -r /opt/app/build/.env.local.php /opt/app/.env.local.php;\
rm -R /opt/app/build;

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD ["docker-healthcheck"]
EXPOSE 9000
CMD ["php-fpm"]


FROM php_builder as app_test
RUN set -eux; \
rm -R /opt/app/prod; \
mv /opt/app/build /opt/app;

FROM nginx:1.17-alpine AS nginx

COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /opt/app

COPY --from=app /opt/app/public ./public